# This file was generated by GoReleaser. DO NOT EDIT.
cask "summond" do
  version "0.0.9"

  on_macos do
    on_intel do
      sha256 "29f9563bd6b1ca49fcb62bb049dcca971e5a02b8f85ef00bd0d030c39b73d767"
      url "https://github.com/joshgummersall/summond/releases/download/v#{version}/summond-darwin-amd64"
      binary "summond-darwin-amd64", target: "summond"
    end
    on_arm do
      sha256 "ece8984c9e2d7c08dc1a99360c5deda32a2c8066b7c116be32ee92f72d748afb"
      url "https://github.com/joshgummersall/summond/releases/download/v#{version}/summond-darwin-arm64"
      binary "summond-darwin-arm64", target: "summond"
    end
  end

  name "summond"
  desc "Schedule and manage macOS background jobs without writing a single plist"
  homepage "https://github.com/joshgummersall/summond"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
