# This file was generated by GoReleaser. DO NOT EDIT.
cask "summond" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "eb400aed50ea713b156cde2854a1ac23612b1dcbde7f84dc17247672c819c4e0"
      url "https://github.com/joshgummersall/summond/releases/download/v#{version}/summond-darwin-amd64"
      binary "summond-darwin-amd64", target: "summond"
    end
    on_arm do
      sha256 "e7dd7b8216317d8a3b13db9aae7b40065062d2bcbdba3dd0fc668f276eb330b9"
      url "https://github.com/joshgummersall/summond/releases/download/v#{version}/summond-darwin-arm64"
      binary "summond-darwin-arm64", target: "summond"
    end
  end

  name "summond"
  desc "Schedule and manage macOS background jobs without writing a single plist"
  homepage "https://github.com/joshgummersall/summond"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  uninstall launchctl: [
      "com.joshgummersall.summond.*",
    ]

  zap launchctl: [
      "com.joshgummersall.summond.*",
    ],
    trash: [
      "~/Library/LaunchAgents/com.joshgummersall.summond.*.plist",
      "~/Library/Application Support/summond",
    ]

end
