# This file was generated by GoReleaser. DO NOT EDIT.
cask "summond" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "5fb8ba42237740872fb1d2cb8704c6e357f452f63f72bc2ebbc277e97ab8160a"
      url "https://github.com/joshgummersall/summond/releases/download/v#{version}/summond-darwin-arm64"
      binary "summond-darwin-arm64", target: "summond"
    end
    on_intel do
      sha256 "8a796c46364dc04e304fdf92b5c5519c4a3d5ab1e1ff699abde34f76fbc590b5"
      url "https://github.com/joshgummersall/summond/releases/download/v#{version}/summond-darwin-amd64"
      binary "summond-darwin-amd64", target: "summond"
    end
  end

  name "summond"
  desc "Schedule and manage macOS background jobs without writing a single plist"
  homepage "https://github.com/joshgummersall/summond"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  uninstall launchctl: [
      "com.joshgummersall.summond.*",
    ]

  zap launchctl: [
      "com.joshgummersall.summond.*",
    ],
    trash: [
      "~/Library/LaunchAgents/com.joshgummersall.summond.*.plist",
      "~/Library/Application Support/summond",
    ]

end
